drop table if exists person_domain CASCADE 
drop table if exists vehicle_domain CASCADE 
create table person_domain (id bigint generated by default as identity, address varchar(255), first_name varchar(255) not null, phone varchar(255), surname varchar(255), primary key (id))
create table vehicle_domain (id bigint generated by default as identity, make varchar(255), model varchar(255), registration_number varchar(255) not null, keeper_id bigint, primary key (id))
alter table vehicle_domain add constraint FK1s2h24ae3cy24vl1xccfmypnn foreign key (keeper_id) references person_domain on delete cascade